"""initial_waveform_chronicles

Revision ID: 4a92509476ce
Revises: 
Create Date: 2026-02-05 20:01:32.387826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a92509476ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waveform_chronicles',
    sa.Column('chronicle_id', sa.Integer(), nullable=False),
    sa.Column('ticker_sigil', sa.String(length=12), nullable=False),
    sa.Column('wavelength_signature', sa.String(length=64), nullable=False),
    sa.Column('harmonic_certainty', sa.Float(), nullable=False),
    sa.Column('temporal_anchor', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('chronicle_id')
    )
    op.create_index(op.f('ix_waveform_chronicles_chronicle_id'), 'waveform_chronicles', ['chronicle_id'], unique=False)
    op.create_index(op.f('ix_waveform_chronicles_ticker_sigil'), 'waveform_chronicles', ['ticker_sigil'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waveform_chronicles_ticker_sigil'), table_name='waveform_chronicles')
    op.drop_index(op.f('ix_waveform_chronicles_chronicle_id'), table_name='waveform_chronicles')
    op.drop_table('waveform_chronicles')
    # ### end Alembic commands ###
